name: Dev Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Setup kyrptconfig
        run: |
          git clone https://github.com/kyrptonaught/kyrptconfig -b 1.21
          cd kyrptconfig
          chmod +x gradlew
          ./gradlew build publishToMavenLocal --no-daemon
          cd ..
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/
